"""adds date column

Revision ID: 5c5678d2a0c4
Revises: 32b9be8971cb
Create Date: 2020-03-14 23:42:49.224170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5678d2a0c4'
down_revision = '32b9be8971cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'date')
    # ### end Alembic commands ###
